# Aplicação
spring.application.name=petcare-api

# Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/petcare_db
spring.datasource.username=postgres
spring.datasource.password=petcare2712

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Inicialização do banco (data.sql)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# JWT
api.security.token.secret=suachavesecreta

# Resend (e-mail)
resend.api.key=re_4QHPTAkL_E6sTqEYTcmG4ZkSF3TC7HAwf


